"""Roster picker: a tiny local web UI to choose the debate lineup.

The Coordinator launches this; the *human* picks the number of adversaries and a
model per seat from the live OpenRouter catalog in a browser, then clicks Submit.
On submit we write three things and shut the server down:

  1. the project's `config.toml` (the roster the debate client actually reads),
  2. the global "last roster" at ~/.coauthor/last_roster.json (so a brand-new
     project can "use most recent"),
  3. an `--out` JSON echo of the choices (for logging / the Coordinator to read).

Zero dependencies on purpose (stdlib http.server + urllib) — the plugin promises
"nothing to install to run a round", and the picker keeps that promise. Runs
foreground and BLOCKS until Submit (or --timeout), so the Coordinator can just
run it and read config.toml afterward.

Usage (the Coordinator runs this via Bash):
    PYTHONPATH=.../src python3 -m coauthor.roster_app \
        --config ./.coauthor/config.toml --out ./.coauthor/logs/roster_echo.json \
        [--port 0] [--timeout 900]
"""
from __future__ import annotations

import argparse
import json
import os
import threading
import urllib.request
import webbrowser
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

OPENROUTER_MODELS_URL = "https://openrouter.ai/api/v1/models"
GLOBAL_LAST = Path.home() / ".coauthor" / "last_roster.json"

# A sensible cross-family starting lineup if there is no remembered roster.
DEFAULT_ROSTER = {
    "seats": [
        {"seat": "proposer", "model": "google/gemini-3.1-pro-preview",
         "charter": "proposer", "temperature": 0.9},
        {"seat": "adversary", "model": "openai/gpt-5.6-sol",
         "charter": "adversary", "temperature": 0.4},
    ]
}


def fetch_models() -> list[dict]:
    """Live OpenRouter catalog, filtered to text->text chat models, newest-ish
    first within each family. No API key needed — this endpoint is public."""
    req = urllib.request.Request(
        OPENROUTER_MODELS_URL, headers={"User-Agent": "coauthor-roster"}
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.loads(resp.read().decode("utf-8"))["data"]
    out = []
    for m in data:
        arch = m.get("architecture", {}) or {}
        in_mods = arch.get("input_modalities") or []
        out_mods = arch.get("output_modalities") or ["text"]
        # Keep pure text chat: text out, and not image/embedding endpoints.
        if "text" not in out_mods or out_mods != ["text"]:
            continue
        mid = m["id"]
        if any(x in mid for x in ("-image", "embedding", "tts", "whisper")):
            continue
        pricing = m.get("pricing", {}) or {}
        out.append({
            "id": mid,
            "family": mid.split("/", 1)[0],
            "name": m.get("name", mid),
            "context": m.get("context_length") or arch.get("context_length") or 0,
            "prompt": pricing.get("prompt", ""),
            "completion": pricing.get("completion", ""),
            "vision": "image" in in_mods,
        })
    out.sort(key=lambda x: (x["family"], x["id"]))
    return out


def load_last_roster() -> dict:
    if GLOBAL_LAST.exists():
        try:
            return json.loads(GLOBAL_LAST.read_text())
        except (json.JSONDecodeError, OSError):
            pass
    return DEFAULT_ROSTER


def render_config_toml(roster: dict) -> str:
    """Regenerate config.toml from a chosen roster. config.toml IS the roster, so
    we own the whole file — header comments + one [seats.<name>] table each."""
    lines = [
        "# coauthor debate-voice roster — generated by the roster picker.",
        "# Edit by hand or re-run /coauthor:roster. Proposer vs adversaries should",
        "# be DIFFERENT model families (that cross-family diversity is the point).",
        "",
    ]
    for s in roster["seats"]:
        lines.append(f"[seats.{s['seat']}]")
        lines.append(f'model = "{s["model"]}"')
        # Only emit `charter` when it differs from the seat name (the default).
        if s.get("charter") and s["charter"] != s["seat"]:
            lines.append(f'charter = "{s["charter"]}"')
        lines.append(f"temperature = {s.get('temperature', 0.7)}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_page(models: list[dict], last: dict) -> str:
    payload = json.dumps({"models": models, "last": last})
    # Single self-contained page: model catalog + per-seat selectors + Submit.
    return _PAGE_TEMPLATE.replace("__PAYLOAD__", payload)


class _State:
    submitted = threading.Event()
    result: dict | None = None
    config_path: Path
    out_path: Path | None


def _make_handler(models, last):
    page = build_page(models, last).encode("utf-8")

    class Handler(BaseHTTPRequestHandler):
        def log_message(self, *a):  # quiet
            pass

        def do_GET(self):
            if self.path not in ("/", "/index.html"):
                self.send_error(404)
                return
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(page)))
            self.end_headers()
            self.wfile.write(page)

        def do_POST(self):
            if self.path != "/submit":
                self.send_error(404)
                return
            n = int(self.headers.get("Content-Length", 0))
            body = json.loads(self.rfile.read(n).decode("utf-8"))
            roster = {"seats": body["seats"]}

            # 1) project config.toml (what the debate client reads)
            _State.config_path.write_text(render_config_toml(roster))
            # 2) global "last roster"
            GLOBAL_LAST.parent.mkdir(parents=True, exist_ok=True)
            GLOBAL_LAST.write_text(json.dumps(roster, indent=2))
            # 3) out echo
            if _State.out_path:
                _State.out_path.write_text(json.dumps(roster, indent=2))

            _State.result = roster
            msg = json.dumps({"ok": True, "seats": roster["seats"]}).encode()
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(msg)))
            self.end_headers()
            self.wfile.write(msg)
            _State.submitted.set()

    return Handler


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", required=True, help="project config.toml to write")
    ap.add_argument("--out", help="optional JSON echo of the chosen roster")
    ap.add_argument("--port", type=int, default=0, help="0 = pick a free port")
    ap.add_argument("--timeout", type=int, default=900, help="seconds to wait for Submit")
    ap.add_argument("--no-browser", action="store_true", help="don't auto-open a browser")
    args = ap.parse_args()

    _State.config_path = Path(args.config).resolve()
    _State.out_path = Path(args.out).resolve() if args.out else None

    models = fetch_models()
    last = load_last_roster()

    httpd = ThreadingHTTPServer(("127.0.0.1", args.port), _make_handler(models, last))
    port = httpd.server_address[1]
    url = f"http://127.0.0.1:{port}/"
    t = threading.Thread(target=httpd.serve_forever, daemon=True)
    t.start()
    print(f"Roster picker at {url}  ({len(models)} models)  — waiting for Submit…")
    if not args.no_browser and not os.environ.get("COAUTHOR_NO_BROWSER"):
        try:
            webbrowser.open(url)
        except Exception:
            pass

    ok = _State.submitted.wait(timeout=args.timeout)
    httpd.shutdown()
    if not ok:
        raise SystemExit(f"No selection within {args.timeout}s — roster unchanged.")
    print(f"Wrote roster ({len(_State.result['seats'])} seats) to {_State.config_path}")
    for s in _State.result["seats"]:
        print(f"  {s['seat']:12s} {s['model']}  (T={s.get('temperature')})")


_PAGE_TEMPLATE = r"""<!doctype html>
<html><head><meta charset="utf-8"><title>coauthor — pick the debate roster</title>
<style>
  :root { color-scheme: light dark; }
  body { font: 15px/1.5 system-ui, sans-serif; margin: 0; padding: 2rem;
         max-width: 1100px; margin-inline: auto; }
  h1 { font-size: 1.4rem; margin: 0 0 .25rem; }
  p.sub { color: #888; margin: 0 0 1.5rem; }
  .seat { border: 1px solid #8884; border-radius: 10px; padding: 1rem 1.25rem;
          margin-bottom: .75rem; }
  .seat h3 { margin: 0 0 .5rem; font-size: 1rem; }
  .seat select, .seat input { font: inherit; padding: .35rem .5rem; }
  .seat select { min-width: 380px; }
  label { display: inline-block; min-width: 90px; color: #888; }
  .row { margin: .3rem 0; }
  .controls { display: flex; gap: 1rem; align-items: center; margin-bottom: 1rem;
              flex-wrap: wrap; }
  button { font: inherit; padding: .55rem 1.4rem; border-radius: 8px;
           border: 0; background: #3b6ef6; color: #fff; cursor: pointer; }
  button.secondary { background: #8883; color: inherit; }
  #done { display:none; padding: 1rem; border-radius: 10px; background: #2ecc7122;
          border: 1px solid #2ecc71; margin-top: 1rem; }
  table { border-collapse: collapse; width: 100%; margin-top: .5rem; font-size: 13px; }
  th, td { text-align: left; padding: .25rem .5rem; border-bottom: 1px solid #8882; }
  #catalog { max-height: 260px; overflow: auto; border: 1px solid #8884;
             border-radius: 8px; margin-top: .5rem; }
  #filter { width: 260px; }
  details { margin-top: 1.5rem; }
  .warn { color: #e67e22; font-size: 13px; min-height: 1.2em; }
</style></head><body>
<h1>Pick the debate roster</h1>
<p class="sub">Proposer + one or more adversaries. Keep the families different —
that cross-family diversity is what breaks correlated errors.</p>

<div class="controls">
  <label style="min-width:auto">Adversaries</label>
  <select id="nadv"><option>1</option><option>2</option><option>3</option><option>4</option></select>
  <button class="secondary" id="recent">Use most recent</button>
</div>

<div id="seats"></div>
<div class="warn" id="warn"></div>
<button id="submit">Submit roster</button>
<div id="done">Roster saved. You can close this tab and return to the Coordinator.</div>

<details>
  <summary>Browse the live OpenRouter catalog (<span id="count"></span> text models)</summary>
  <input id="filter" placeholder="filter by id / family…">
  <div id="catalog"></div>
</details>

<script>
const DATA = __PAYLOAD__;
const MODELS = DATA.models, LAST = DATA.last;
const byId = Object.fromEntries(MODELS.map(m => [m.id, m]));

function optionsHtml(selected) {
  let fam = null, html = "";
  for (const m of MODELS) {
    if (m.family !== fam) { if (fam) html += "</optgroup>"; fam = m.family;
      html += `<optgroup label="${fam}">`; }
    const price = m.prompt ? ` — $${(+m.prompt*1e6).toFixed(2)}/$${(+m.completion*1e6).toFixed(2)} per M` : "";
    const ctx = m.context ? ` — ${(m.context/1000)|0}k` : "";
    const sel = m.id === selected ? " selected" : "";
    html += `<option value="${m.id}"${sel}>${m.id}${ctx}${price}</option>`;
  }
  return html + "</optgroup>";
}

function seatCard(seat, model, temp, idx) {
  const label = seat === "proposer" ? "Proposer (creative lead)"
              : `Adversary ${idx}`;
  return `<div class="seat" data-seat="${seat}" data-charter="${seat==='proposer'?'proposer':'adversary'}">
    <h3>${label}</h3>
    <div class="row"><label>Model</label>
      <select class="model">${optionsHtml(model)}</select></div>
    <div class="row"><label>Temperature</label>
      <input class="temp" type="number" step="0.1" min="0" max="2" value="${temp}"
             style="width:80px"></div>
  </div>`;
}

function render(seats) {
  const prop = seats.find(s => s.seat === "proposer")
            || {model: MODELS[0].id, temperature: 0.9};
  const advs = seats.filter(s => s.seat !== "proposer");
  const n = Math.max(1, Math.min(4, advs.length || 1));
  document.getElementById("nadv").value = n;
  let html = seatCard("proposer", prop.model, prop.temperature ?? 0.9, 0);
  for (let i = 0; i < n; i++) {
    const a = advs[i] || {model: (MODELS[1]||MODELS[0]).id, temperature: 0.4};
    const seat = i === 0 ? "adversary" : `adversary_${i+1}`;
    html += seatCard(seat, a.model, a.temperature ?? 0.4, i+1);
  }
  document.getElementById("seats").innerHTML = html;
}

function currentSeats() {
  return [...document.querySelectorAll(".seat")].map(el => ({
    seat: el.dataset.seat,
    charter: el.dataset.charter,
    model: el.querySelector(".model").value,
    temperature: parseFloat(el.querySelector(".temp").value),
  }));
}

document.getElementById("nadv").addEventListener("change", () => {
  const seats = currentSeats();               // preserve current picks
  const prop = seats[0];
  const advs = seats.slice(1);
  const n = +document.getElementById("nadv").value;
  const next = [prop];
  for (let i=0;i<n;i++) next.push(advs[i] || {seat:"adversary", model:(MODELS[1]||MODELS[0]).id, temperature:0.4});
  render(next);
});

document.getElementById("recent").addEventListener("click", () => render(LAST.seats));

document.getElementById("submit").addEventListener("click", async () => {
  const seats = currentSeats();
  const fams = seats.map(s => byId[s.model]?.family);
  const warn = document.getElementById("warn");
  if (new Set(fams).size < fams.length)
    warn.textContent = "Note: two seats share a model family — diversity is reduced (submitting anyway).";
  else warn.textContent = "";
  const r = await fetch("/submit", {method:"POST", body: JSON.stringify({seats})});
  if (r.ok) { document.getElementById("submit").disabled = true;
              document.getElementById("done").style.display = "block"; }
});

// catalog table
document.getElementById("count").textContent = MODELS.length;
function catalog(filter) {
  const f = (filter||"").toLowerCase();
  const rows = MODELS.filter(m => m.id.toLowerCase().includes(f))
    .map(m => `<tr><td>${m.id}</td><td>${(m.context/1000|0)}k</td>
      <td>${m.prompt?('$'+(+m.prompt*1e6).toFixed(2)):'—'}</td></tr>`).join("");
  document.getElementById("catalog").innerHTML =
    `<table><thead><tr><th>model</th><th>ctx</th><th>$/M in</th></tr></thead><tbody>${rows}</tbody></table>`;
}
document.getElementById("filter").addEventListener("input", e => catalog(e.target.value));
catalog("");
render(LAST.seats || []);
</script></body></html>"""


if __name__ == "__main__":
    main()
